let suggestions = [
  "Bad Bunny",
  "Taylor Swift",
  "BTS",
  "Drake",
  "Justin Bieber",
  "The Weeknd",
  "J Balvin",
  "Ariana Grande",
  "Olivia Rodrigo",
  "Juice WRLD",
  "Dua Lipa",
  "Rauw Alejandro",
  "Ed Sheeran",
  "Eminem",
  "BTS",
  "Kanye West",
  "Billie Eilish",
  "Coldplay",
  "Imagine Dragons",
  "XXXTENTACION",
  "Ozuna",
  "Rihanna",
  "Maroon 5",
  "Travis Scott",
  "David Guetta",
  "Shawn Mendes",
  "Bruno Mars",
  "Nicki Minaj",
  "Adele",
  "Selena Gomez",
  "Harry Styles",
  "Maluma",
  "Katy Perry",
  "Doja Cat",
  "Farruko",
  "Shakira",
  "OneRepublic",
  "Miley Cyrus",
  "Metallica",
  "Wiz Khalifa",
];
